##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Copyright © dev-cetera.com & contributors.
##
## The use of this source code is governed by an MIT-style license described in
## the LICENSE file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_router
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_router
funding:
- https://www.patreon.com/c/t0mb3rr
- https://github.com/sponsors/t0mb3rr
- https://www.buymeacoffee.com/dev_cetera
description: A lightweight router designed for ease of use and efficient state management. 
version: 0.5.1
topics:
  - router
  - navigation
  - state-management

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  df_log: ^0.3.20
  df_pod: ^0.18.10
  df_pwa_utils: ^0.3.3
  df_safer_dart: ^0.17.3

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.5
  df_safer_dart_lints: ^0.3.3

