name: df_router_simple_example
homepage: https://dev-cetera.com/


publish_to: none
version: 0.1.0
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  df_router:
    path: ../../
dev_dependencies:
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

